containers:
  mongodb:
    image: mongo:3.6.23
    volumes:
      - local: ./database
        container: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_DATABASE: auth
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: tribes
      ME_CONFIG_MONGODB_SERVER: host.docker.internal
    ports:
      - '8081:8081'
    volumes: 
      - ./data:/data/db      
tasks:
  run-db:
    description: Initialize DB
    run: 
      container: mongodb
  run-express:
    run:
      container: mongo-express

  